defaults: &defaults
  working_directory: ~/neptune
  docker:
    - image: circleci/node:10.6-browsers
version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - persist_to_workspace:
          root: .
          paths:
            - '*'
#  test:
#    <<: *defaults
#    steps:
#      - attach_workspace:
#          at: .
#      - run:
#          name: Test
#          command: npm test
  deploy-docs-to-root:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build docs
          command: npm run build-docs
      - run:
          name: Deploy docs
          command: |
            mkdir ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            git config --global user.email "circleci@transferwise.com"
            git config --global user.name "CircleCI"
            npm run deploy-docs
  deploy-docs-for-branch:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build docs
          command: npm run build-docs
      - run:
          name: Deploy docs
          command: |
            mkdir ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            git config --global user.email "circleci@transferwise.com"
            git config --global user.name "CircleCI"
            npm run deploy-docs-for-branch
#  publish:
#    <<: *defaults
#    steps:
#      - run:
#          name: Setup npm token
#          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN_PUBLISH" >> ~/.npmrc
#      - attach_workspace:
#          at: .
#      - run:
#          name: Build
#          command: npm run build
#      - run:
#          name: Publish on npm
#          command: npm publish --access=public
#  release:
#    <<: *defaults
#    steps:
#      - attach_workspace:
#          at: .
#      - run:
#          name: Release to GitHub
#          command: |
#            mkdir ~/.ssh
#            ssh-keyscan github.com >> ~/.ssh/known_hosts
#            npm run release-to-github

workflows:
  version: 2
  build-test-release-and-build-docs:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
#      - test:
#          requires:
#            - build
      - deploy-docs-to-root:
          context: frontend-publish
#          requires:
#            - test
          filters:
            branches:
              only: master
      - deploy-docs-for-branch:
#          requires:
#            - test
          filters:
            branches:
              ignore:
                - gh-pages
                - master
#      - publish:
#          context: frontend-publish
#          requires:
#            - deploy-docs-to-root
#          filters:
#            branches:
#              only: master
#      - release:
#          context: frontend-publish
#          requires:
#            - publish
#          filters:
#            branches:
#              only: master